(role xp)
(role op)
(init (control xp))
(legal xp noop)
(legal op noop)
(open)
(undrawn 0 0 0 0)
(cell 1 1 xp)
(move 1 2 3)
(init (control xp))
(<= (next (control xp))      (true (control op)))
(<= (next (control op))      (true (control xp)))
(<= terminal (not open))
(<= (transfer ?k) (does ?k noop ))
; (<= any_undrawn (undrawn ?x1 ?y1 ?x2 ?y2))
(<= (legal2 ?role (move 1 2 3)) (true (control ?role)))
(<= (opencell ?x ?y) (true (control xp)) (not (true (cell ?x ?y xp))) (not (true (cell ?x ?y op))))
